name: plan_track
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.3.0
  flutter_secure_storage: ^8.0.0
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.5.3
  table_calendar: ^3.2.0
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true
